[Service]
Host = "edgex-ui-go"
Port = 4500
Labels = []
OpenMsg = "edgeX ui started"
StaticResourcesPath = "./static"

#Using an default memory db if not configed.
[Database]
Host = "localhost"
Name = "edgex-ui-go"
Port = 27017
Username = "su"
Password = "su"
  [Database.Scheme]
  User = "user"
  Gateway = "gateway"

[DynamicProxy]
ObjectPath     = "/object"
ObjectPort     = "5000"
MonitorPath     = "/monitor"
MonitorPort     = "5000"

CoreDataPath     = "/core-data"
CoreDataPort     = "48080"
CoreMetadataPath = "/core-metadata"
CoreMetadataPort = "48081"
CoreCommandPath  = "/core-command"
CoreCommandPort  = "48082"
CoreExportPath   = "/core-export"
CoreExportPort   = "48071"
RuleEnginePath   = "/rule-engine"
RuleEnginePort   = "48075"
SupportLoggingPath   = "/support-logging"
SupportLoggingPort   = "48061"
SupportNotificationPath   = "/support-notification"
SupportNotificationPort   = "48060"
SupportSchedulerPath   = "/support-scheduler"
SupportSchedulerPort   = "48085"
